dynaconf_merge: true
default:
  NAME: user_service
  HOST: 0.0.0.0
  PORT: 8002
  FAST_API_PATH: src.application.app:user_app
  LOG_LEVEL: info
  RELOADED: True
  POSTGRES:
    dialect: asyncpg
    host: postgres
    port: 5432
    login: postgres
    password: postgres
    database: postgres
    pgbouncer: False
    echo: False
    pool_min_size: 10
    pool_max_size: 20
    pool_timeout: 90
    mat_view_time: 15
  RABBIT_MQ:
    host: rabbit_mq
    port: 5672
    login: rabbit_mq
    password: rabbit_mq
    protocol: amqp
    timeout: 20
  RABBIT_ROUTING_KEYS:
    test_routing_key: test_routing_key
