"""init models

Revision ID: a3b12e89ebbb
Revises:
Create Date: 2025-03-16 21:36:29.335574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3b12e89ebbb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Человекочитаемое название разрешения",
        ),
        sa.Column(
            "layer",
            sa.String(),
            nullable=False,
            comment="К чему относится разрешение ('frontend'/'backend'/...)",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_permissions_uuid"), "permissions", ["uuid"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_uuid"), "roles", ["uuid"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "first_name",
            sa.String(),
            nullable=False,
            comment="Имя пользователя",
        ),
        sa.Column(
            "last_name",
            sa.String(),
            nullable=False,
            comment="Фамилия пользователя",
        ),
        sa.Column(
            "patronymic",
            sa.String(),
            nullable=False,
            comment="Отчество пользователя",
        ),
        sa.Column("login", sa.String(), nullable=False, comment="Логин пользователя"),
        sa.Column(
            "password",
            sa.Text(),
            nullable=False,
            comment="Зашифрованный пароль пользователя",
        ),
        sa.Column("email", sa.String(), nullable=False, comment="Email пользователя"),
        sa.Column("age", sa.Integer(), nullable=False, comment="Возраст пользователя"),
        sa.Column(
            "phone_number",
            sa.String(),
            nullable=False,
            comment="Телефонный номер пользователя",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Статус подтверждения",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="Статус супер-пользователя",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Статус активности",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("permission_uuid", sa.UUID(), nullable=False),
        sa.Column("role_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["permission_uuid"],
            ["permissions.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["roles.uuid"],
        ),
        sa.PrimaryKeyConstraint("permission_uuid", "role_uuid", "uuid"),
        sa.UniqueConstraint(
            "permission_uuid", "role_uuid", name="idx_unique_role_permission"
        ),
    )
    op.create_index(
        op.f("ix_role_permissions_uuid"),
        "role_permissions",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("role_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["roles.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("user_uuid", "role_uuid", "uuid"),
        sa.UniqueConstraint("user_uuid", "role_uuid", name="idx_unique_user_role"),
    )
    op.create_index(op.f("ix_user_roles_uuid"), "user_roles", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_uuid"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_uuid"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_uuid"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_uuid"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
